### ISSUE TITLE
Question about adjusting 'case' parameter in Poisson_2d class

### ISSUE THREAD

**Issue by ccdzz** [zezhongzhang/TransNet#1]
Hello,

I'm working with the `ls.ipynb` file in the `TransNet/PDE_Poisson_2d_annulus/` directory. In the third code block, I noticed the following line:

```python
my_prob = Poisson_2d(case=1, data=data)
```
I appreciate that the author has provided a way to adjust the true solution and the right-hand side source term by changing the `case` value. This demonstrates the transferability of the method.

However, I've encountered an issue: when I change the `case` value to 2, 3, or 4, the resulting MSE (Mean Squared Error) is not as good as expected.

Questions:

Is this behavior expected?
If not, what could be causing this discrepancy?
Are there any recommended adjustments or additional steps I should take when changing the `case` value to maintain good MSE results?
Any insights or suggestions on how to address this would be greatly appreciated. Thank you for your time and assistance!

**Comment by ccdzz** [comment]
Upon changing the `case` value to 2, I observed that the resulting MSE curve exhibits significantly higher values than expected. Despite my attempts to fine-tune the `shape_vec` parameter to improve accuracy, I was unable to achieve satisfactory results.
<img width="554" alt="image" src="https://github.com/user-attachments/assets/57864c80-0753-4c0a-b9e7-3fccc82e0a35">

**Comment by zezhongzhang** [comment]
The reason for getting this bad MSE is because the "u_true" for comparison is inconsistent with the computed PDE solution. In "ls.ipynb", the "u_true" is loaded from the "data/data.npz" file which is generated only for case 1. To test other cases, you need to run "problem_setup.ipynb" with corresponding case numbers and this generate a new "data/data.npz" with the correct "u_true" for MSE computation. Then, the "ls.ipynb" should produce the correct MSE.

**Comment by ccdzz** [comment]
Thank you for your answer.
